<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-17 14:00

=======
# Generated by Django 5.1.1 on 2024-10-10 01:06

import django.db.models.deletion
from django.conf import settings
>>>>>>> a84e5f83cd7e48777f0f2fca6d92b28d67a321f1
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> a84e5f83cd7e48777f0f2fca6d92b28d67a321f1
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
=======
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_token', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_token', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
>>>>>>> a84e5f83cd7e48777f0f2fca6d92b28d67a321f1
        ),
    ]
